parameters:

services:
    bc_bootstrap.twig.icon_extension:
        class: Bc\Bundle\BootstrapBundle\Twig\BootstrapIconExtension
        tags:
            - { name: twig.extension }
    bc_bootstrap.twig.label_extension:
        class: Bc\Bundle\BootstrapBundle\Twig\BootstrapLabelExtension
        tags:
            - { name: twig.extension }
    bc_bootstrap.twig.badge_extension:
        class: Bc\Bundle\BootstrapBundle\Twig\BootstrapBadgeExtension
        tags:
            - { name: twig.extension }

    bc_bootstrap.flash:
        class: Bc\Bundle\BootstrapBundle\Session\FlashMessage
        arguments:
            - @session

    bc_bootstrap.form.type.collection:
        class: Bc\Bundle\BootstrapBundle\Form\Type\BootstrapCollectionType
        tags:
            - { name: form.type, alias: bootstrap_collection }

    bc_bootstrap.form.extension.typesetter_extension:
        class: Bc\Bundle\BootstrapBundle\Form\Extension\TypeSetterExtension
        tags:
            - { name: form.type_extension, alias: form }

